"""Add OnboardingApproval table and new columns to TeamStatus

Revision ID: 4aaccd8b8bf7
Revises: 
Create Date: 2025-05-20 21:50:28.134094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aaccd8b8bf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tentative_start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('shift', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('laptop_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('asset_tag', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('manager_vaco_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hr_poc', sa.String(length=100), nullable=True))
        batch_op.alter_column('employee_company_email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('temp_id')
        batch_op.drop_column('onboarding_checklist_json')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('team_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_company_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_status', schema=None) as batch_op:
        batch_op.drop_column('job_title')
        batch_op.drop_column('employee_company_email')

    with op.batch_alter_table('onboarding_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('onboarding_checklist_json', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('temp_id', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('employee_company_email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('hr_poc')
        batch_op.drop_column('project_name')
        batch_op.drop_column('manager_vaco_id')
        batch_op.drop_column('asset_tag')
        batch_op.drop_column('laptop_id')
        batch_op.drop_column('location')
        batch_op.drop_column('shift')
        batch_op.drop_column('tentative_start_date')

    # ### end Alembic commands ###
